//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facalty
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_ids { get; set; }
        public string user_names { get; set; }
        public string user_add { get; set; }
        public Nullable<int> user_age { get; set; }
        public Nullable<System.DateTime> date_join { get; set; }
        public string date_description { get; set; }
    }
}
